[workspace]
members = [
    "bin/cli",
    "bin/utxo-spend",
    "bin/signing",
    "tests",
    "crates/node",
    "crates/protocol",
    "crates/types",
    "crates/clients",
]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.37.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
futures = "0.3.30"
serde_json = "1.0"
frost-secp256k1 = "2.1.0"
bitcoin = { version = "0.32.6", features = ["rand-std"] }
libp2p = { version = "0.54", features = [
    "noise",
    "ping",
    "tcp",
    "tokio",
    "yamux",
    "request-response",
    "macros",
    "identify",
    "gossipsub",
    "mdns",
    "quic",
    "cbor",
] }
hex = "0.4"
rand = "0.9.1"
esplora-client = { version = "0.12.0", default-features = false, features = [
    "async-https",
    "tokio",
] }
bincode = { version = "2.0.1", features = ["serde"] }
sha2 = "0.10.9"
rocksdb = "0.23.0"
async-trait = "0.1.88"
dotenvy = "0.15.7"
bip39 = "2.1.0"
base64 = "0.22.1"
tonic = "0.13"
getrandom = "0.2.16"
wasi = "0.11.0+wasi-snapshot-preview1"
bitcoin-internals = "0.2.0"
bitcoin_hashes = "0.13.0"
bitflags = "2.9.1"
embedded-io = "0.6.1"
h2 = "0.4.10"
hex-conservative = "0.2.1"
http = "1.3.1"
http-body = "1.0.1"
hyper = "1.6.0"
rand_chacha = "0.9.0"
rand_core = "0.9.3"
regex-automata = "0.4.9"
regex-syntax = "0.8.5"
ring = "0.17.14"
rustls-webpki = "0.103.3"
spin = "0.9.8"
thiserror = "2.0.12"
thiserror-impl = "2.0.12"
unsigned-varint = "0.8.0"
untrusted = "0.9.0"
windows-sys = "0.52.0"
yamux = "0.13.5"

[workspace.lints.rust]
unsafe_code = "warn"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
correctness = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }
doc_markdown = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
missing_safety_doc = "allow"
cargo_common_metadata = "allow"