[workspace]
members = [
    "experiments/dkg",
    "experiments/networking",
    "experiments/taproot",
    "experiments/cli",
    "node",
]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.37.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
futures = "0.3.30"
serde_json = "1.0"
frost-secp256k1 = "2.1.0"
bitcoin = { version = "0.32.6", features = ["rand-std"] }
libp2p = { version = "0.54", features = [
    "noise",
    "ping",
    "tcp",
    "tokio",
    "yamux",
    "request-response",
    "macros",
    "identify",
    "gossipsub",
    "mdns",
    "quic",
    "cbor",
] }
hex = "0.4"
rand = "0.9.1"
