services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    image: vault-node
    environment:
      - KEY_PASSWORD=
      - IS_TESTNET=true
    entrypoint: "/app/cli run --key-file-path one.json --config-file-path one.yaml"
    ports:
      - "50051:50051"
    volumes:
      - ./keys/one.json:/app/one.json
      - ./keys/one.yaml:/app/one.yaml
    networks:
      - vaultnet

  node2:
    image: vault-node
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - KEY_PASSWORD=
      - IS_TESTNET=true
    entrypoint: "/app/cli run --key-file-path two.json --config-file-path two.yaml"
    volumes:
      - ./keys/two.json:/app/two.json
      - ./keys/two.yaml:/app/two.yaml
    networks:
      - vaultnet

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    image: vault-node
    environment:
      - KEY_PASSWORD=
      - IS_TESTNET=true
    entrypoint: "/app/cli run --key-file-path three.json --config-file-path three.yaml"
    volumes:
      - ./keys/three.json:/app/three.json
      - ./keys/three.yaml:/app/three.yaml
    networks:
      - vaultnet

  node4:
    build:
      context: .
      dockerfile: Dockerfile
    image: vault-node
    environment:
      - KEY_PASSWORD=
      - IS_TESTNET=true
    entrypoint: "/app/cli run --key-file-path four.json --config-file-path four.yaml"
    volumes:
      - ./keys/four.json:/app/four.json
      - ./keys/four.yaml:/app/four.yaml
    networks:
      - vaultnet

  node5:
    build:
      context: .
      dockerfile: Dockerfile
    image: vault-node
    environment:
      - KEY_PASSWORD=
      - IS_TESTNET=true
    entrypoint: "/app/cli run --key-file-path five.json --config-file-path five.yaml"
    volumes:
      - ./keys/five.json:/app/five.json
      - ./keys/five.yaml:/app/five.yaml
    networks:
      - vaultnet

networks:
  vaultnet:
    driver: bridge
