[package]
name = "withdrawal"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true


[dependencies]
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
tonic = { workspace = true }
node = { path = "../../crates/node" } 