[package]
name = "withdrawal"
version = "0.1.0"
edition = "2021"
description = "Withdrawal signing utility for the Threshold network"
license = "MIT"
repository = "https://github.com/onthreshold/threshold/"
keywords = ["bitcoin", "cryptocurrency", "wallet", "withdrawal"]
categories = ["cryptography", "blockchain"]

[lints]
workspace = true


[dependencies]
clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
tonic = { workspace = true }
node = { path = "../../crates/node" } 