[package]
name = "cli"
version = "0.1.0"
edition = "2021"
description = "Command-line interface for the Threshold network"
license = "MIT"
keywords = ["bitcoin", "cryptocurrency", "wallet", "cli"]
categories = ["cryptography", "blockchain"]

[dependencies]
tokio = { workspace = true, features = ["full", "macros", "rt-multi-thread"] }
node = { path = "../../crates/node" }
types = { path = "../../crates/types" }
libp2p = { workspace = true, features = ["ed25519"] }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
clap = { version = "4.4", features = ["derive"] }
bs58 = "0.5"
directories = "6.0.0"
argon2 = "0.5"
aes-gcm = "0.10"
base64 = "0.22.1"
rpassword = "7.2"
dotenvy = "0.15.7"
derive_more = { version = "2.0.1", features = ["full"] }
tonic = { workspace = true }

[dev-dependencies]
tempfile = "3.8"
assert_matches = "1.5"

[lints]
workspace = true