[package]
name = "types"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["full"] }
tokio = { workspace = true }
rocksdb = { workspace = true }

[lints]
workspace = true