[package]
name = "utxo-spend"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { workspace = true }
tokio = { workspace = true, features = ["full"] }
bip39 = { version = "2.0.0", features = ["rand"] }
node = { path = "../../crates/node" }
esplora-client = { version = "0.12.0", features = ["async"] }
hex = "0.4"
dotenvy = "0.15"

[dev-dependencies]
tempfile = "3.8"
assert_matches = "1.5"
