[package]
name = "utxo-spend"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
bitcoin = { workspace = true }
tokio = { workspace = true, features = ["full"] }
bip39 = { workspace = true, features = ["rand"] }
esplora-client = { version = "0.12.0", features = ["async"] }
hex = "0.4"
dotenvy = { workspace = true }
node = { path = "../../crates/node" }
protocol = { path = "../../crates/protocol" }

[dev-dependencies]
tempfile = "3.8"
assert_matches = "1.5"
