name: Code Coverage PR

on:
  pull_request:

jobs:
  test:
    runs-on: blacksmith-16vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: Caching Rust Dependencies
        uses: useblacksmith/cache@v5
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup update 1.87
      - run: rustup default 1.87
      - run: cargo install cargo-tarpaulin
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libclang-dev clang
      - name: Run Code Coverage
        env:
          MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
          IS_TESTNET: "true"
        run: cargo test --all
        run: |
          cargo tarpaulin --all-targets --exclude-files "target/*" --count --out xml
        env:
          MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
          IS_TESTNET: "true"
      - name: Post Coverage Comment on PR
        if: github.event_name == 'pull_request'
        uses: 5monkeys/cobertura-action@v14
        with:
          path: cobertura.xml
          minimum_coverage: 0
          show_branch: true
          show_line: true
